set_property CLOCK_DEDICATED_ROUTE FALSE [get_nets clk_IBUF]
set_property -dict {PACKAGE_PIN U7 IOSTANDARD LVCMOS18} [get_ports rst]
set_property -dict {PACKAGE_PIN G22 IOSTANDARD LVCMOS18} [get_ports clk]
set_property -dict {PACKAGE_PIN F15 IOSTANDARD LVCMOS18} [get_ports out[3]]
set_property -dict {PACKAGE_PIN F13 IOSTANDARD LVCMOS18} [get_ports out[2]]
set_property -dict {PACKAGE_PIN F14 IOSTANDARD LVCMOS18} [get_ports out[1]]
set_property -dict {PACKAGE_PIN F16 IOSTANDARD LVCMOS18} [get_ports out[0]]
set_property -dict {PACKAGE_PIN J4 IOSTANDARD LVCMOS18} [get_ports updown]
set_property -dict {PACKAGE_PIN D20 IOSTANDARD LVCMOS18} [get_ports display[0]]
set_property -dict {PACKAGE_PIN C20 IOSTANDARD LVCMOS18} [get_ports display[1]]
set_property -dict {PACKAGE_PIN C22 IOSTANDARD LVCMOS18} [get_ports display[2]]
set_property -dict {PACKAGE_PIN B22 IOSTANDARD LVCMOS18} [get_ports display[3]]
set_property -dict {PACKAGE_PIN B21 IOSTANDARD LVCMOS18} [get_ports display[4]]
set_property -dict {PACKAGE_PIN A21 IOSTANDARD LVCMOS18} [get_ports display[5]]
set_property -dict {PACKAGE_PIN E22 IOSTANDARD LVCMOS18} [get_ports display[6]]
set_property -dict {PACKAGE_PIN D22 IOSTANDARD LVCMOS18} [get_ports DP]
set_property -dict {PACKAGE_PIN D16 IOSTANDARD LVCMOS18} [get_ports digit]  